AISLE_SEEDS: dict[str, str] = {
    # ── Produce ──────────────────────────────────────────────────────────────
    "garlic": "Produce",
    "onion": "Produce",
    "red onion": "Produce",
    "yellow onion": "Produce",
    "white onion": "Produce",
    "shallot": "Produce",
    "scallion": "Produce",
    "green onion": "Produce",
    "chive": "Produce",
    "ginger": "Produce",
    "lemon": "Produce",
    "lime": "Produce",
    "orange": "Produce",
    "celery": "Produce",
    "carrot": "Produce",
    "parsnip": "Produce",
    "tomato": "Produce",
    "cherry tomato": "Produce",
    "grape tomato": "Produce",
    "cucumber": "Produce",
    "zucchini": "Produce",
    "yellow squash": "Produce",
    "bell pepper": "Produce",
    "red bell pepper": "Produce",
    "green bell pepper": "Produce",
    "yellow bell pepper": "Produce",
    "jalapeño": "Produce",
    "jalapeno": "Produce",
    "serrano pepper": "Produce",
    "poblano": "Produce",
    "lettuce": "Produce",
    "romaine": "Produce",
    "spinach": "Produce",
    "kale": "Produce",
    "arugula": "Produce",
    "mixed greens": "Produce",
    "broccoli": "Produce",
    "cauliflower": "Produce",
    "broccolini": "Produce",
    "asparagus": "Produce",
    "green beans": "Produce",
    "snap peas": "Produce",
    "snow peas": "Produce",
    "corn": "Produce",
    "mushroom": "Produce",
    "cremini mushroom": "Produce",
    "shiitake mushroom": "Produce",
    "portobello mushroom": "Produce",
    "button mushroom": "Produce",
    "potato": "Produce",
    "russet potato": "Produce",
    "yukon gold potato": "Produce",
    "sweet potato": "Produce",
    "yam": "Produce",
    "avocado": "Produce",
    "eggplant": "Produce",
    "fennel": "Produce",
    "leek": "Produce",
    "beet": "Produce",
    "radish": "Produce",
    "cabbage": "Produce",
    "brussels sprouts": "Produce",
    "bok choy": "Produce",
    "parsley": "Produce",
    "cilantro": "Produce",
    "basil": "Produce",
    "mint": "Produce",
    "dill": "Produce",
    "tarragon": "Produce",
    "thyme": "Produce",
    "rosemary": "Produce",
    "sage": "Produce",
    "oregano": "Produce",
    "chives": "Produce",

    # ── Meat & Seafood ────────────────────────────────────────────────────────
    "chicken breast": "Meat & Seafood",
    "chicken thigh": "Meat & Seafood",
    "chicken": "Meat & Seafood",
    "ground chicken": "Meat & Seafood",
    "whole chicken": "Meat & Seafood",
    "chicken leg": "Meat & Seafood",
    "rotisserie chicken": "Meat & Seafood",
    "ground beef": "Meat & Seafood",
    "beef": "Meat & Seafood",
    "steak": "Meat & Seafood",
    "chuck roast": "Meat & Seafood",
    "short ribs": "Meat & Seafood",
    "brisket": "Meat & Seafood",
    "pork": "Meat & Seafood",
    "pork chop": "Meat & Seafood",
    "pork tenderloin": "Meat & Seafood",
    "ground pork": "Meat & Seafood",
    "pork belly": "Meat & Seafood",
    "pork shoulder": "Meat & Seafood",
    "ham": "Meat & Seafood",
    "prosciutto": "Meat & Seafood",
    "pancetta": "Meat & Seafood",
    "bacon": "Meat & Seafood",
    "sausage": "Meat & Seafood",
    "italian sausage": "Meat & Seafood",
    "chorizo": "Meat & Seafood",
    "andouille": "Meat & Seafood",
    "lamb": "Meat & Seafood",
    "ground lamb": "Meat & Seafood",
    "lamb chop": "Meat & Seafood",
    "turkey": "Meat & Seafood",
    "ground turkey": "Meat & Seafood",
    "turkey breast": "Meat & Seafood",
    "duck": "Meat & Seafood",
    "duck breast": "Meat & Seafood",
    "salmon": "Meat & Seafood",
    "tuna": "Meat & Seafood",
    "cod": "Meat & Seafood",
    "halibut": "Meat & Seafood",
    "tilapia": "Meat & Seafood",
    "shrimp": "Meat & Seafood",
    "scallop": "Meat & Seafood",
    "crab": "Meat & Seafood",
    "lobster": "Meat & Seafood",
    "clam": "Meat & Seafood",
    "mussel": "Meat & Seafood",
    "anchovy": "Meat & Seafood",

    # ── Dairy & Eggs ──────────────────────────────────────────────────────────
    "egg": "Dairy & Eggs",
    "large egg": "Dairy & Eggs",
    "butter": "Dairy & Eggs",
    "unsalted butter": "Dairy & Eggs",
    "salted butter": "Dairy & Eggs",
    "milk": "Dairy & Eggs",
    "whole milk": "Dairy & Eggs",
    "skim milk": "Dairy & Eggs",
    "heavy cream": "Dairy & Eggs",
    "heavy whipping cream": "Dairy & Eggs",
    "whipping cream": "Dairy & Eggs",
    "light cream": "Dairy & Eggs",
    "half and half": "Dairy & Eggs",
    "sour cream": "Dairy & Eggs",
    "crème fraîche": "Dairy & Eggs",
    "creme fraiche": "Dairy & Eggs",
    "cream cheese": "Dairy & Eggs",
    "yogurt": "Dairy & Eggs",
    "greek yogurt": "Dairy & Eggs",
    "parmesan": "Dairy & Eggs",
    "parmigiano-reggiano": "Dairy & Eggs",
    "pecorino": "Dairy & Eggs",
    "mozzarella": "Dairy & Eggs",
    "fresh mozzarella": "Dairy & Eggs",
    "burrata": "Dairy & Eggs",
    "cheddar": "Dairy & Eggs",
    "gruyère": "Dairy & Eggs",
    "gruyere": "Dairy & Eggs",
    "swiss cheese": "Dairy & Eggs",
    "provolone": "Dairy & Eggs",
    "fontina": "Dairy & Eggs",
    "gouda": "Dairy & Eggs",
    "brie": "Dairy & Eggs",
    "feta": "Dairy & Eggs",
    "goat cheese": "Dairy & Eggs",
    "ricotta": "Dairy & Eggs",
    "cottage cheese": "Dairy & Eggs",
    "mascarpone": "Dairy & Eggs",
    "buttermilk": "Dairy & Eggs",

    # ── Pantry ────────────────────────────────────────────────────────────────
    "all-purpose flour": "Pantry",
    "bread flour": "Pantry",
    "whole wheat flour": "Pantry",
    "rice flour": "Pantry",
    "flour": "Pantry",
    "sugar": "Pantry",
    "granulated sugar": "Pantry",
    "brown sugar": "Pantry",
    "powdered sugar": "Pantry",
    "salt": "Pantry",
    "kosher salt": "Pantry",
    "black pepper": "Pantry",
    "rice": "Pantry",
    "white rice": "Pantry",
    "brown rice": "Pantry",
    "jasmine rice": "Pantry",
    "basmati rice": "Pantry",
    "arborio rice": "Pantry",
    "pasta": "Pantry",
    "spaghetti": "Pantry",
    "penne": "Pantry",
    "fettuccine": "Pantry",
    "rigatoni": "Pantry",
    "linguine": "Pantry",
    "orzo": "Pantry",
    "egg noodles": "Pantry",
    "bread crumbs": "Pantry",
    "panko": "Pantry",
    "cornstarch": "Pantry",
    "baking soda": "Pantry",
    "baking powder": "Pantry",
    "yeast": "Pantry",
    "oats": "Pantry",
    "rolled oats": "Pantry",
    "lentils": "Pantry",
    "red lentils": "Pantry",
    "chickpeas": "Pantry",
    "black beans": "Pantry",
    "kidney beans": "Pantry",
    "cannellini beans": "Pantry",
    "white beans": "Pantry",
    "quinoa": "Pantry",
    "couscous": "Pantry",
    "polenta": "Pantry",
    "farro": "Pantry",
    "barley": "Pantry",
    "bulgur": "Pantry",
    "bread": "Pantry",
    "sourdough": "Pantry",
    "pita": "Pantry",
    "tortilla": "Pantry",
    "naan": "Pantry",

    # ── Spices & Herbs ────────────────────────────────────────────────────────
    "cumin": "Spices & Herbs",
    "coriander": "Spices & Herbs",
    "coriander seed": "Spices & Herbs",
    "paprika": "Spices & Herbs",
    "smoked paprika": "Spices & Herbs",
    "turmeric": "Spices & Herbs",
    "cayenne": "Spices & Herbs",
    "chili powder": "Spices & Herbs",
    "dried oregano": "Spices & Herbs",
    "dried thyme": "Spices & Herbs",
    "dried rosemary": "Spices & Herbs",
    "dried basil": "Spices & Herbs",
    "bay leaf": "Spices & Herbs",
    "bay leaves": "Spices & Herbs",
    "cinnamon": "Spices & Herbs",
    "nutmeg": "Spices & Herbs",
    "cardamom": "Spices & Herbs",
    "allspice": "Spices & Herbs",
    "cloves": "Spices & Herbs",
    "garlic powder": "Spices & Herbs",
    "onion powder": "Spices & Herbs",
    "red pepper flakes": "Spices & Herbs",
    "crushed red pepper": "Spices & Herbs",
    "fennel seed": "Spices & Herbs",
    "mustard seed": "Spices & Herbs",
    "celery seed": "Spices & Herbs",
    "caraway seed": "Spices & Herbs",
    "sumac": "Spices & Herbs",
    "garam masala": "Spices & Herbs",
    "curry powder": "Spices & Herbs",
    "za'atar": "Spices & Herbs",
    "ras el hanout": "Spices & Herbs",
    "star anise": "Spices & Herbs",
    "five spice": "Spices & Herbs",
    "vanilla extract": "Spices & Herbs",

    # ── Oils & Vinegars ───────────────────────────────────────────────────────
    "olive oil": "Oils & Vinegars",
    "extra virgin olive oil": "Oils & Vinegars",
    "light olive oil": "Oils & Vinegars",
    "vegetable oil": "Oils & Vinegars",
    "canola oil": "Oils & Vinegars",
    "sunflower oil": "Oils & Vinegars",
    "grapeseed oil": "Oils & Vinegars",
    "peanut oil": "Oils & Vinegars",
    "sesame oil": "Oils & Vinegars",
    "toasted sesame oil": "Oils & Vinegars",
    "coconut oil": "Oils & Vinegars",
    "red wine vinegar": "Oils & Vinegars",
    "white wine vinegar": "Oils & Vinegars",
    "apple cider vinegar": "Oils & Vinegars",
    "balsamic vinegar": "Oils & Vinegars",
    "rice vinegar": "Oils & Vinegars",
    "sherry vinegar": "Oils & Vinegars",
    "white vinegar": "Oils & Vinegars",

    # ── Condiments & Sauces ───────────────────────────────────────────────────
    "soy sauce": "Condiments & Sauces",
    "tamari": "Condiments & Sauces",
    "coconut aminos": "Condiments & Sauces",
    "fish sauce": "Condiments & Sauces",
    "hot sauce": "Condiments & Sauces",
    "sriracha": "Condiments & Sauces",
    "sambal oelek": "Condiments & Sauces",
    "worcestershire sauce": "Condiments & Sauces",
    "ketchup": "Condiments & Sauces",
    "mustard": "Condiments & Sauces",
    "dijon mustard": "Condiments & Sauces",
    "whole grain mustard": "Condiments & Sauces",
    "mayonnaise": "Condiments & Sauces",
    "tahini": "Condiments & Sauces",
    "miso": "Condiments & Sauces",
    "white miso": "Condiments & Sauces",
    "red miso": "Condiments & Sauces",
    "hoisin sauce": "Condiments & Sauces",
    "oyster sauce": "Condiments & Sauces",
    "teriyaki sauce": "Condiments & Sauces",
    "tomato paste": "Condiments & Sauces",
    "honey": "Condiments & Sauces",
    "maple syrup": "Condiments & Sauces",
    "barbecue sauce": "Condiments & Sauces",

    # ── Canned Goods ──────────────────────────────────────────────────────────
    "diced tomatoes": "Canned Goods",
    "crushed tomatoes": "Canned Goods",
    "whole peeled tomatoes": "Canned Goods",
    "tomato sauce": "Canned Goods",
    "coconut milk": "Canned Goods",
    "light coconut milk": "Canned Goods",
    "coconut cream": "Canned Goods",
    "chicken broth": "Canned Goods",
    "chicken stock": "Canned Goods",
    "vegetable broth": "Canned Goods",
    "vegetable stock": "Canned Goods",
    "beef broth": "Canned Goods",
    "beef stock": "Canned Goods",
    "canned chickpeas": "Canned Goods",
    "canned black beans": "Canned Goods",
    "canned white beans": "Canned Goods",
    "canned corn": "Canned Goods",
    "canned tuna": "Canned Goods",
    "canned anchovies": "Canned Goods",
    "artichoke hearts": "Canned Goods",

    # ── Baking ────────────────────────────────────────────────────────────────
    "chocolate chips": "Baking",
    "cocoa powder": "Baking",
    "dark chocolate": "Baking",
    "milk chocolate": "Baking",
    "white chocolate": "Baking",
    "bittersweet chocolate": "Baking",
    "almond flour": "Baking",
    "cream of tartar": "Baking",
    "gelatin": "Baking",
    "vanilla": "Baking",

    # ── Alcohol ───────────────────────────────────────────────────────────────
    "white wine": "Alcohol",
    "red wine": "Alcohol",
    "dry white wine": "Alcohol",
    "dry red wine": "Alcohol",
    "beer": "Alcohol",
    "bourbon": "Alcohol",
    "whiskey": "Alcohol",
    "rum": "Alcohol",
    "vodka": "Alcohol",
    "gin": "Alcohol",
    "brandy": "Alcohol",
    "cognac": "Alcohol",
    "dry sherry": "Alcohol",
    "marsala wine": "Alcohol",
    "sake": "Alcohol",
    "mirin": "Alcohol",
    "shaoxing wine": "Alcohol",
    "rice wine": "Alcohol",
}
